### ISSUE TITLE
Dockerfile uses ubuntu

### ISSUE THREAD

**Issue by GreenStage** [bancodobrasil/stop-analyzing-api#22]
The current dockerfile uses Ubuntu as the base image ~180Mb. 

Maybe alphine (~5Mb) would be a better fit? Or is there something we need from ubuntu?

**Comment by tiagostutz** [comment]
I'm big fan of Alpine and use it in some projects when the project is stable and being released to production. But, when the project is in its early stages, sometimes we need a "backdoor" to do some tests on the fly inside the container by editing some files, requesting (curl) around some resources, stuff like that. For that kind of job, I prefer Debian (Ubuntu) because it is more dev friendly.
 
I think we could go with [debian:buster-slim](https://hub.docker.com/layers/debian/library/debian/buster-slim/images/sha256-1e103da3d714a9f737aa6b2fb722b72e1218afa080503e5a1cb7eb4bd1b09fdf?context=explore) which is Debian and is 69MB and could work on a Alpine image when the first stable release of the project launches. This could even be a separate repo with different OS Docker image flavors.

What do you think?

**Comment by GreenStage** [comment]
got it!
