### ISSUE TITLE
I would like to contribute :)

### ISSUE THREAD

**Issue by eniovalo** [bancodobrasil/stop-analyzing-api#3]
Hi,
I don't know Go and Prisma, but I would love learn it. =]
Can I help in anything?

Thanks.

**Comment by tiagostutz** [comment]
Hi @eniovalo,

Nice to have you here!... I'm sure this will be a greate starting point. I suggest you to do the [Go track of exercism.io](https://exercism.io/tracks/go) at the same time you contribute here to get into some specifics of Golang.

I'll create a issue for you here that will be a appropriate for your learning path. I'll come back here as soon as the issue is created.

**Comment by eniovalo** [comment]
Hi @tiagostutz ,
Thanks for the opportunity. =]
I will do the Go track of exercism.io while wait for the issue. :)

**Comment by tiagostutz** [comment]
Hey @eniovalo! 👋 

I just created this issue #7. How about that? If you want to take this, please comment o the issue and I'll assign it to you right away!

**Comment by eniovalo** [comment]
Hi @tiagostutz,
Thanks. =]
I would like to take this issue #7 .
